services:
  hydra-migrate:
    image: oryd/hydra:v2.2.0
    environment:
      - DSN=memory
    command: migrate -c /etc/config/hydra/hydra.yml sql -e --yes
    volumes:
      - type: bind
        source: ./hydra
        target: /etc/config/hydra
    restart: on-failure

  hydra:
    image: oryd/hydra:v2.2.0
    ports:
      - "4444:4444" # Public port
      - "4445:4445" # Admin port
    command: serve -c /etc/config/hydra/hydra.yml all --dev
    volumes:
      - type: bind
        source: ./hydra
        target: /etc/config/hydra
    environment:
      - DSN=memory
    restart: unless-stopped
    depends_on:
      - hydra-migrate

  # Mock consent/login app
  hydra-login-consent:
    image: oryd/hydra-login-consent-node:v2.2.0
    ports:
      - "3000:3000"
    environment:
      - HYDRA_ADMIN_URL=http://hydra:4445
      - NODE_TLS_REJECT_UNAUTHORIZED=0
    restart: unless-stopped
    depends_on:
      - hydra