apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: promptql-docs
  name: promptql-docs
  namespace: hasura
spec:
  replicas: 2
  selector:
    matchLabels:
      app: promptql-docs
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 2
  template:
    metadata:
      labels:
        app: promptql-docs
    spec:
      containers:
        - name: promptql-docs
          image: us-west1-docker.pkg.dev/websitecloud-352908/promptql-docs/promptql-docs:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              protocol: TCP
          env:
            - name: PORT
              value: '8080'
            - name: release_mode
              value: 'RELEASE_MODE_PLACEHOLDER'
            - name: OPENREPLAY_INGEST_POINT
              valueFrom:
                secretKeyRef:
                  name: ddn-docs
                  key:  OPENREPLAY_INGEST_POINT
            - name: OPENREPLAY_PROJECT_KEY
              valueFrom:
                secretKeyRef:
                  name: ddn-docs
                  key:  OPENREPLAY_PROJECT_KEY
          readinessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 20
          resources:
            requests:
              memory: '64Mi'
              cpu: '3m'
            limits:
              memory: '512Mi'
              cpu: '250m'
