apiVersion: v1
kind: Service
metadata:
  labels:
    app: promptql-docs
    hasuraService: custom
  name: promptql-docs
  namespace: hasura
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app: promptql-docs
  sessionAffinity: None
  type: ClusterIP
