name: Merge Main to Release Stage

on:
  push:
    branches:
      - main

jobs:
  update-staging:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Merge Main to Release Stage
        run: |
          git config user.name "hasura-bot"
          git config user.email "accounts@hasura.io"

          # we'll pull the latest changes from main
          git pull origin main

          # then, we'll merge main into release-stage and take `main` if there's any conflicts
          git checkout release-stage
          git merge -X theirs origin/main -m "Merge main into release-stage"

          # and push the changes
          git push origin release-stage

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
