name: Update LLM Docs

on:
  push:
    branches:
      - main

jobs:
  update-and-commit:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Check for changes in /docs
        id: check_docs_changes
        run: |
          if git diff --name-only HEAD^ HEAD | grep '^docs/'; then
            echo "should_run=true" >> "$GITHUB_OUTPUT"
          else
            echo "No changes in /docs."
            echo "should_run=false" >> "$GITHUB_OUTPUT"
          fi

      - name: Set up Bun
        if: steps.check_docs_changes.outputs.should_run == 'true'
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        if: steps.check_docs_changes.outputs.should_run == 'true'
        working-directory: utilities/one-click-llm
        run: bun install

      - name: Run Bun script
        if: steps.check_docs_changes.outputs.should_run == 'true'
        working-directory: utilities/one-click-llm
        run: bun run start

      - name: Commit and push changes
        if: steps.check_docs_changes.outputs.should_run == 'true'
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git add -u
          if git diff --cached --quiet; then
            echo "No changes to commit."
            exit 0
          fi

          git commit -m "Chore: update LLM markdown"
          git push https://x-access-token:${{ secrets.DOCS_GITHUB_TOKEN }}@github.com/${{ github.repository }} HEAD:main --force
        env:
          GITHUB_TOKEN: ${{ secrets.DOCS_GITHUB_TOKEN }}
